FROM node:20-alpine AS builder

WORKDIR /app/frontend

COPY package*.json /app/
COPY frontend/package*.json ./
RUN npm install

COPY . /app

ARG VITE_API_BASE_URL=http://localhost:3000
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}

RUN npm run build

FROM nginx:1.27-alpine

COPY --from=builder /app/frontend/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
